name: --Platzhalter--
version: 1.2
main: me.iTreon.test.main.Main

commands:
   heal:
      description: Heilt dich oder einen Spieler
      usage: /heal [Spieler]
   Items:
      description: Öffnet ein Inventar - Aktuell einen Mülleimer
      usage: /items
   Gm:
      description: Wechselt zwischen Creative und Survival Modus
      usage: /gm
   rules:
      description: Zeigt die Regeln
      usage: /rules [Seite]
   tp:
      description: Teleportieren - Mal anders...
      usage: /tp [Spieler]|/tp [Spieler1] [Spieler2]|/tp [Koordinaten]