name: Test
version: 1.2
main: me.iTreon.test.main.Main

commands:
   heal:
      description: Heilt!
   Items:
      description: oeffnetaaaaaaaaaa
   Gm:
      description: sss
   rules:
      description: sss